apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cf-ingress
  namespace: default
#below might be useful for troubleshooting
  #annotations:
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/from-to-www-redirect: "true"

spec:
  ingressClassName: nginx
  rules:
  - host: mongo.fi-hiqpublic.cftenant.com 
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: mongo-express-service
            port: 
              number: 8081
  - host: web-service.fi-hiqpublic.cftenant.com 
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: web-service
            port: 
              number: 80