---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2025.4.0
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials
      # Create a config.yaml file from the ConfigMap below.
      - name: config
        configMap:
          name: cloudflared
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
# Move this service down to replace the one in the config.yaml for "cloudflared as ingress controller"
#service: http://mongo-express-service.default.svc.cluster.local:8081
# Move this service down to replace the one in the config.yaml for "cloudflared to nginx"
#service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
data:
  config.yaml: |
    tunnel: e6271233-abcb-40e1-9eca-ce21b3347ceb
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    noTLSVerify: true
    ingress:
    - hostname: mong.fi-hiqpublic.cftenant.com
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
    - service: http_status:404