apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongo
  namespace: mongo
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  #- Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: mongo