apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secrets
  namespace: default
type: Opaque
data:
  web-service: {{ .Values.data.webService | b64enc }}
  mongo-express-service: {{ .Values.data.mongoExpressService | b64enc }} 